kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # Role ko describe karte hain
  # Example name "argocd-snapshot-access"
  name: argocd-snapshot-access
rules:
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - list
